### ISSUE TITLE
models/ subdirectory missing?

### ISSUE THREAD

**Issue by bml1g12** [Jamiroquai88/VBDiarization#5]
How can one obtain the mentioned subdirectory containing pre-trained models?

../models/GMM.h5
../models/v400_iter5.h5
../models/pldaa.h5

As I cannot find them in this repo. 

It also says "It is possible to score even without PLDA model, see config file configs/vbdiar_no-PLDA.yml." 

However this file: vbdiar_no-PLDA.yml, is missing. 

Thank you

**Comment by Jamiroquai88** [comment]
sorry, it is not possible to share models due to licensing, etc.

i-vector models can be found here: http://voicebiometry.org/ - should be more or less compatible with existing code, at least GMM and T-Matrix

x-vector models can be found here https://david-ryan-snyder.github.io/2017/10/04/model_sre16_v2.html

**Comment by Jamiroquai88** [comment]
hi, current master is now fully compatible with x-vectors, code was completely rewritten
